services:

  ciscos_fantasy:
    build:
      context: ./
      dockerfile: docker/ciscos_fantasy/Dockerfile
    container_name: ciscos_fantasy
    image: ciscos_fantasy
    ports:
      - 25565:25565
    environment:
      EULA: True
      INIT_MEMORY: 16G
      MAX_MEMORY: 24G
      VERSION: "1.19.2"
      FORGE_VERSION: "43.3.5"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: "CARPG Ultimate V7b Serv.zip"

    # RAM-DISK
    # volumes:
    # - ./ram_disk:/data

    # DATA FS:
    volumes:
    - ./data:/data
    restart: unless-stopped

networks:
  default:
    name: ciscos_fantasy
